-- ============================================================
-- NEMO 운영 스키마 (PostgreSQL)
-- ============================================================
-- 생성 방법:  cd backend && ./gradlew exportPostgresSchema
-- 원본:       backend/build/generated-schema/schema-postgres.sql
-- 생성 시각:  2026-08-21
--
-- 왜 이 파일이 필요한가:
--   운영 프로필은 ddl-auto: validate 다. 스키마를 자동으로 만들지 않는다.
--   비어 있는 DB에 붙이면 애플리케이션이 아예 기동하지 않는다.
--   누군가 먼저 테이블을 만들어 줘야 하고, 그게 이 파일이다.
--
--   운영 DB에 ddl-auto: update 를 한 번 켜서 만드는 방법도 있지만 쓰지 않는다.
--   무엇이 실행되는지 보지 못한 채 스키마가 바뀌고 되돌릴 방법도 남지 않는다.
--
-- ⚠️ 아직 Flyway/Liquibase 같은 마이그레이션 도구가 없다.
--    지금은 수동 절차이며, 도구를 도입하면 이 파일을 정식 마이그레이션으로 옮겨야 한다.
--
-- ⚠️ 이 파일은 엔티티에서 자동 생성한 것이다. 직접 고치지 말고
--    엔티티를 고친 뒤 위 명령으로 다시 뽑아라.
--
-- 적용:
--   Supabase 대시보드 → SQL Editor 에 붙여넣기 (가장 간단)
--   또는 Session pooler 로 psql:
--     psql "postgresql://postgres.uzdzvqmqfqvltchmlxwl@aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres" \
--          -f tools/schema/sql/schema-postgres.sql
--
--   ⚠️ 직결 주소(db.<ref>.supabase.co)는 쓰지 마라. IPv4 주소가 없다(IPv6 전용).
--      기본 VPC 의 EC2 에는 IPv6 가 없어 붙지 않는다. 실측:
--        db.<ref>.supabase.co                    → IPv6 만
--        aws-0-ap-northeast-2.pooler.supabase.com → IPv4 3개, 5432/6543 열림
--
--   ⚠️ Transaction pooler(6543) 말고 Session pooler(5432) 를 쓴다.
--      Transaction 모드는 prepared statement 를 유지하지 않아 JPA/Hibernate 와 궁합이 나쁘다.
--
-- 적용 후 확인:
--   SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename;
--   → album, album_favorite, album_photos, album_share, friend,
--     photo_tag, photos, refresh_tokens, storage_cleanup_task, timeline, users
--
-- ⚠️ 이 파일을 적용한 직후 반드시 02-revoke-postgrest-exposure.sql 도 적용하라.
--    Supabase 는 public 스키마를 PostgREST 로 자동 노출한다.
--    이것만 돌리면 anon 키만으로 users(비밀번호 해시)와
--    refresh_tokens(세션 토큰)까지 읽고 쓸 수 있는 상태가 된다.
--
-- 참고: 조회 성능 인덱스는 별도다 → tools/performance/sql/indexes.sql
-- ============================================================


    create table album (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        cover_photo_url varchar(255),
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table album_favorite (
        album_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        primary key (id),
        constraint uk_album_favorite_album_user unique (album_id, user_id)
    );

    -- ⚠️ sequence 컬럼과 기본키는 여기서 만들지 않는다.
    --    Flyway V1__album_photo_and_photo_tag.sql 이 추가한다.
    --    여기서 미리 만들면 "column already exists" 로 기동이 실패한다.
    create table album_photos (
        album_id bigint not null,
        photo_id bigint not null
    );

    create table album_share (
        active boolean not null,
        album_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        role varchar(20) not null check (role in ('VIEWER','EDITOR','CO_OWNER')),
        status varchar(20) not null check (status in ('PENDING','ACCEPTED','REJECTED')),
        primary key (id),
        constraint uk_album_share_album_user unique (album_id, user_id)
    );

    create table friend (
        created_at timestamp(6) not null,
        friend_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        status varchar(255) not null check (status in ('PENDING','ACCEPTED','REJECTED')),
        primary key (id),
        unique (user_id, friend_id)
    );

    -- ⚠️ photo_tag 테이블은 여기서 만들지 않는다.
    --    Flyway V1 이 CHECK 제약(position 0~1)과 인덱스까지 포함해 만든다.

    create table photos (
        deleted boolean,
        favorite boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        taken_at timestamp(6),
        user_id bigint,
        memo varchar(300),
        brand varchar(255),
        image_url varchar(255) not null,
        location varchar(255),
        thumbnail_url varchar(255),
        primary key (id)
    );

    create table refresh_tokens (
        expiry timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        token varchar(512) not null unique,
        primary key (id)
    );

    create table storage_cleanup_task (
        retry_count integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        next_attempt_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        status varchar(20) not null check (status in ('PENDING','PROCESSING','COMPLETED','FAILED')),
        reason varchar(30) not null check (reason in ('UPLOAD_ROLLBACK','PHOTO_DELETED')),
        last_error varchar(500),
        object_key varchar(512) not null,
        primary key (id)
    );

    create table timeline (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        photo_id bigint not null,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        content varchar(255),
        primary key (id)
    );

    create table users (
        login_fail_count integer not null,
        max_photo_count integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_login_failed_at timestamp(6),
        locked_until timestamp(6),
        updated_at timestamp(6) not null,
        plan_type varchar(20) not null,
        email varchar(191) not null unique,
        nickname varchar(255),
        password varchar(255) not null,
        profile_image_url varchar(255),
        provider varchar(255),
        social_id varchar(255),
        primary key (id)
    );

    create index ix_refresh_tokens_user 
       on refresh_tokens (user_id);

    create index idx_cleanup_status_next_attempt 
       on storage_cleanup_task (status, next_attempt_at);

    alter table if exists album 
       add constraint FKf8jilwyp6s7bb1ruw11u94808 
       foreign key (user_id) 
       references users;

    alter table if exists album_favorite 
       add constraint FK8fib3qlx3hp40rhefym8aggtf 
       foreign key (album_id) 
       references album;

    alter table if exists album_favorite 
       add constraint FK49hdhwwcvpduc47iniwmomhhm 
       foreign key (user_id) 
       references users;

    alter table if exists album_photos 
       add constraint FKe296symku8rj4gyxboas1fvph 
       foreign key (album_id) 
       references album;

    alter table if exists album_photos 
       add constraint FKpr9st8wurjfrr2snruxy4wva6 
       foreign key (photo_id) 
       references photos;

    alter table if exists album_share 
       add constraint FK3fl54bd2qyux37w7px5qudclp 
       foreign key (album_id) 
       references album;

    alter table if exists album_share 
       add constraint FK2onsard4efswegve8dgo64vx7 
       foreign key (user_id) 
       references users;

    alter table if exists friend 
       add constraint FK5j28qgyvon52ycu9sfieraerm 
       foreign key (friend_id) 
       references users;

    alter table if exists friend 
       add constraint FKeab81424e9dtc4a8hjlq4xiew 
       foreign key (user_id) 
       references users;



    alter table if exists timeline 
       add constraint FK1h3wift47d21ry5dn2s0rqxvv 
       foreign key (photo_id) 
       references photos;

    alter table if exists timeline 
       add constraint FKtmgghqat5nwgp3ux7lwqy6fyf 
       foreign key (user_id) 
       references users;
