ALTER TABLE album_photos ADD COLUMN sequence INTEGER;

-- 이 인덱스 생성은 중복 멤버십이 있을 때 즉시 실패한다. 기존 행을 임의로 삭제하지 않는다.
CREATE UNIQUE INDEX uk_album_photos_membership_preflight
    ON album_photos (album_id, photo_id);

UPDATE album_photos ap
SET sequence = ranked.sequence
FROM (
    SELECT album_id,
           photo_id,
           CAST(ROW_NUMBER() OVER (PARTITION BY album_id ORDER BY photo_id) - 1 AS INTEGER) AS sequence
    FROM album_photos
) ranked
WHERE ap.album_id = ranked.album_id
  AND ap.photo_id = ranked.photo_id;

ALTER TABLE album_photos ALTER COLUMN sequence SET NOT NULL;
ALTER TABLE album_photos
    ADD CONSTRAINT pk_album_photos PRIMARY KEY (album_id, photo_id);
ALTER TABLE album_photos
    ADD CONSTRAINT uk_album_photos_sequence UNIQUE (album_id, sequence);
DROP INDEX uk_album_photos_membership_preflight;

CREATE TABLE photo_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id BIGINT NOT NULL,
    tagged_user_id BIGINT NOT NULL,
    position_x DOUBLE PRECISION NOT NULL,
    position_y DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_photo_tag_photo FOREIGN KEY (photo_id) REFERENCES photos (id),
    CONSTRAINT fk_photo_tag_user FOREIGN KEY (tagged_user_id) REFERENCES users (id),
    CONSTRAINT uk_photo_tag_photo_user UNIQUE (photo_id, tagged_user_id),
    CONSTRAINT ck_photo_tag_position_x CHECK (position_x >= 0.0 AND position_x <= 1.0),
    CONSTRAINT ck_photo_tag_position_y CHECK (position_y >= 0.0 AND position_y <= 1.0)
);

CREATE INDEX idx_photo_tag_photo_id ON photo_tag (photo_id);
CREATE INDEX idx_photo_tag_tagged_user_id ON photo_tag (tagged_user_id);
